Wdp210601-11new
kamilwilk95/wdp-2106-01 pull request #31
Opened 2021-06-15 13:11 UTC by maciejburak

2021-06-15 16:42 UTC, kamilwilk95 requested changes
Już drobne uwagi

2021-06-15 16:42 UTC, kamilwilk95 commented on src/components/features/NewFurniture/NewFurniture.js
> +
Po co jest pusta linia?

2021-06-15 16:42 UTC, kamilwilk95 commented on src/components/features/NewFurniture/NewFurniture.js
> +
pusta linia

2021-06-15 16:42 UTC, kamilwilk95 commented on src/redux/initialState.js
> +
Pusta linia

2021-06-16 06:30 UTC, wojbiel833 approved these changes

2021-06-16 14:24 UTC, wojbiel833 requested changes
Ulubione produkty mają mieć ten guzik zawsze taki jak na hover (kremowy).

Wszystko pieknie działa tylko guzik ma zły kolor, nie czepiam sie, bron boże ale tak tam napisano :)

2021-06-17 13:05 UTC, maciejburak commented
Wspólnie ustaliliśmy, że w treści taska powinna być zmiana i buttony powinny mieć $darkGrey

2021-06-17 13:20 UTC, kamilwilk95 approved these changes

2021-06-17 13:20 UTC, merged