WDP210601-34
kamilwilk95/wdp-2106-01 pull request #33
Opened 2021-06-16 09:27 UTC by piotrwaloszek

Add Carousel to Feedbacks section

2021-06-16 14:07 UTC, wojbiel833 approved these changes, later dismissed
Jak dla mnie cacy tylko zastanawia mnie czemu część styli jest w globalu?
Fajnie bo RWD jest juz praktycznie załatwione :)
Generalnie komponent identylko jak na designie więc super :D

2021-06-16 14:57 UTC, kamilwilk95 requested changes

2021-06-16 14:57 UTC, kamilwilk95 commented on src/styles/global.scss
> +.feedback{
Dlaczego to jest w global?

2021-06-16 15:01 UTC, piotrwaloszek commented on src/styles/global.scss
> +.feedback{
Wrzuciłem to do global, ponieważ stosuję gotowy komponent "carousel" ściągnięty npm-em, a nie przygotowaną osobną funkcją (jeszcze jej nie mam) i w przypadku jak ktoś chciałby skorzystać z "carousel" w innym elemencie ma od razu gotowe pomarańczowe guziki (nie musi ich pisać od nowa)

2021-06-16 19:52 UTC, kamilwilk95 commented on src/styles/global.scss
> +.feedback{
Ma sens, ale w takim wypadku nadajmy jakies ogólnie klasy, np `carousel` a nie `feedback` bo ciężko żeby ktoś później używając tego komponentu dla produktów używał klasy `feedback` ;)

2021-06-17 10:21 UTC, piotrwaloszek commented on src/styles/global.scss
> +.feedback{
Poprawione

2021-06-17 13:31 UTC, kamilwilk95 approved these changes

2021-06-17 13:31 UTC, merged