WDP210601-21
kamilwilk95/wdp-2106-01 pull request #37
Opened 2021-06-17 12:21 UTC by maciejburak

2021-06-17 12:37 UTC, wojbiel833 requested changes
Przy odświeżeniu strony klient chciałby widzieć od razu "moją ocenę" w co najmniej jednym produkcie, czyli trzeba przykładowe dane wrzucić do stanu początkowego.
Ta czesc nie jest chyba zrealizowana ;)

W komponencie Stars.js troche scisk, dodabym kilka spacji zeby bylo czytelniejsze.
Do reszty raczej nie mozna sie przyczepic :) Sam bym lepiej nie zrobiL :D

2021-06-17 12:46 UTC, wojbiel833 approved these changes, later dismissed
i pieknie :)

2021-06-17 13:42 UTC, kamilwilk95 requested changes

2021-06-17 13:42 UTC, kamilwilk95 commented on src/components/common/Stars/StairsContainer.js
> +const mapDispatchToProps = dispatch => ({
Stairs jest ogólnym komponentem, może być zastosowany w wielu różnych miejscach, np. do oceny komentarzy. Tego typy komponenty nie powinny odpalać żadnych akcji redux-a, bo jest to logika ściśle połączona z daną logiką biznesową i uniemożliwia reużycie komponentu. Komponent `Staer` powinien w propsach przyjmować funkcję `onChangeStar(value)`, a co ma się stać po takiej zmianie powinno być zdefiniowane w kontenerze produktu, uwaga na przyszłość, nie musisz tego porpawiać

2021-06-17 13:42 UTC, kamilwilk95 commented on src/components/common/Stars/Stars.js
> +                  onMouseLeave={() => returnToBasicForm()}
Nie dało by się tego na kontenerze zrobić zamiast na każdej gwiazdce ten sam event?

2021-06-17 13:42 UTC, kamilwilk95 commented on src/components/common/Stars/Stars.js
> +                <FaStar
Bardzo dużo tutaj kodu i dużo się powtarza. Spróbuj to wydzielić do osobnych funkcja które zwrócą JSX. Np. `getStar` a w niej skorzystaj z innych pomocniczych funkcji np. `getStarClassName`, i te funkcje powinno przyjmować to od czego zależą, czyli np. `isHover` `isTouch`

2021-06-18 06:02 UTC, maciejburak commented on src/components/common/Stars/Stars.js
> +                  onMouseLeave={() => returnToBasicForm()}
changeStars( ) i returnToBasicForm() korzystają z hooków lokalnie w Stars.js wolalbym jednak zostawić tak jak jest bo robi się duży bałagan.

2021-06-18 13:43 UTC, kamilwilk95 approved these changes

2021-06-18 13:43 UTC, merged