Wdp210601-28
kamilwilk95/wdp-2106-01 pull request #41
Opened 2021-06-22 09:32 UTC by maciejburak

2021-06-22 10:12 UTC, julia-kocik commented
Komponent wygląda zgodnie z designem.
Po przeklikaniu znika cały slider pod tabami  i pojawia się slider z innymi elementami - działa poprawnie.
Strzałki w sliderze - działają poprawnie (na RWD jest z tego co widzę osobny task).
Kliknięcie na miniaturkę sprawia, że obecne zdjęcie główne znika  i pokazuje się nowe, takie jak na danej miniaturce - również działa poprawnie.
Podsumowując wszystko działa jak powinno w mojej opinii :)

2021-06-22 10:17 UTC, julia-kocik approved these changes, later dismissed

2021-06-22 13:53 UTC, kamilwilk95 requested changes
Jest problem z wcięciami po uruchomieniu projektu, uruchom task `refactor:lint`.

`Strzałki w sliderze miniaturek mają przesuwać ten mały slider o tyle elementów, ile jest widoczne przy danej szerokości ekranu (np. w wersji desktopowej jest ich 6)` to tak nie działa, strzałka pokazuje następne zdjęcie.

2021-06-23 15:24 UTC, kamilwilk95 requested changes

2021-06-23 15:24 UTC, kamilwilk95 commented on src/components/features/Gallery/Gallery.js
> +      if (window.innerWidth > 1200) {
zamiast poraz kolejny robić ifologię możemy skorzystać z `sliderSize()`

2021-06-23 21:32 UTC, kamilwilk95 approved these changes

2021-06-23 21:32 UTC, merged